### ISSUE TITLE
Fix websocket error when reconnecting

### ISSUE THREAD

**Issue by mathturtle** [Kitware/light-viz#10]

**Comment by mathturtle** [comment]
@jourdain If this is the 404 in the console for http://localhost:8080/paraview, then I can't figure it out.  I've traced it back to tonic-io's VtkWeb module, but I can't figure out what needs to be changed.  Do i just need to specify the right URL to connect to in LightVis's code?

**Comment by jourdain** [comment]
The error is expected as we are not using a Launcher (404 => Can't find
launcher)
