### ISSUE TITLE
Fix dataset listing refresh

### ISSUE THREAD

**Issue by mathturtle** [Kitware/light-viz#3]
On the list page, the refresh button should check the file system and do a full refresh instead of using the cached list of file that were there when the server started.

**Comment by mathturtle** [comment]
@jourdain I have a version of this working.... ish.  For some reason the thumbnails don't update right.  Say I have datasets A, B, C and D when I start light-viz.  I then go in and remove B from the data directory.  When I click refresh, I will have datasets A, C and D shown, but C will have B's thumbnail and D will have C's thumbnail.

I figured out how to fix this by disabling all the 'did I already fetch this thumbnail' checks... but do we want to do that?

**Comment by jourdain** [comment]
don't know.
