### ISSUE TITLE
Use paraview's offscreen rendering so the renderwindow doesn't pop up

### ISSUE THREAD

**Issue by mathturtle** [Kitware/light-viz#44]

**Comment by mathturtle** [comment]
I can change it so that the renderwindow is empty by setting UseOffscreenRendering=1 when I create the view, but I don't know how to prevent the window from popping up altogether.

@TristanWright @scottwittenburg: @jourdain said you had done something like this for ERS?  What am I missing?

**Comment by mathturtle** [comment]
@patrickoleary So the change I mentioned above is merged.  It seems that the only way to remove that empty window is to compile paraview with EGL or OSMesa, which isn't really a LightViz issue anymore.

**Comment by patrickoleary** [comment]
This seems fine.

**Comment by mathturtle** [comment]
So @jourdain redid this so that it uses onscreen rendering by default, but you can pass the --offscreen flag to LightViz when you start it to enable offscreen rendering.  Apparently there are some cases where offscreen doesn't work that we want to support.  But it is still done, so I'm closing this.
