### ISSUE TITLE
Color pallette for foreground and background color

### ISSUE THREAD

**Issue by mathturtle** [Kitware/light-viz#5]
Foreground for solid color modules, background for renderer background.

**Comment by mathturtle** [comment]
@jourdain I'm working on this right now.  I've got the server side calls for setting the foreground color working, but I'm curious if you have any ideas about what the UI should look like.  I know you'd mentioned something, but if you could send me a sketch or an example from another tool that would make it a lot easier.

**Comment by jourdain** [comment]
I was thinking a single div by color couple using some css background-color with gradient.
