### ISSUE TITLE
Supported Data types?

### ISSUE THREAD

**Issue by KrbAlmryde** [Kitware/light-viz#59]
Hello,

What data formats are supported and are there any examples demonstrating their use? Under the "Importing Data" section of the documentation there is mention of a data file with the .data extension, but it is unclear if that is simply a placeholder for some other type of well known format, or you really are expecting a .data file. 

I was attempting to test this app with some composite .tiff image data but had some problems. 

Thanks,

Kyle

**Comment by jourdain** [comment]
Hi Kyle,

The supported data format are the one ParaView support. I am in the process of improving the documentation of the ParaViewWeb's projects (Visualizer, LightViz, ArcticViewer...) so hopefully soon enough you will find the appropriate informations of usage.

Thanks for your patience,

Seb

**Comment by KrbAlmryde** [comment]
Hi Seb,

Thanks for the prompt response! I figured as much. Ill keep an eye on the documentation until then and keep playing with the apps in the meantime. Thank you for this wonderful work!

Best,

Kyle

**Comment by KrbAlmryde** [comment]
paraview data formats.

**Comment by jourdain** [comment]
Did you managed to load your data?
