### ISSUE TITLE
Is it possible to run the project without using Webpack?

### ISSUE THREAD

**Issue by rpelorosso** [Kitware/light-viz#63]
Hi! 

As the instructions say, every time I change a .js file I run 

`npm run build`

and refresh the browser. This works, but running `npm run build` takes almost 10 seconds.

Is it possible to skip the use of Webpack during development so I can make the process of testing my changes faster?

thanks!

**Comment by jourdain** [comment]
`npm run build -- --watch`

**Comment by rpelorosso** [comment]
That is so amazing, thank you!
