### ISSUE TITLE
ImportError: cannot import name 'wamp'

### ISSUE THREAD

**Issue by rpelorosso** [Kitware/light-viz#64]
Hi! 

I'm trying to run light-viz, and getting a python error related to wamp. Below is my calling to pvpython (as suggested by `light-viz-cli.js `

```
[silencer@myhostname light-viz]$ /opt/paraview/bin/pvpython -dr "/home/silencer/Desktop/nodejs/light-viz/light-viz/server/pvw-light-viz.py" --content "/home/silencer/Desktop/nodejs/light-viz/light-viz/dist" --port 8080

Traceback (most recent call last):
  File "/home/silencer/Desktop/nodejs/light-viz/light-viz/server/pvw-light-viz.py", line 85, in <module>
    from paraview.web import wamp      as pv_wamp
ImportError: cannot import name 'wamp'

```

Do you know what might be happening? I could't yet figure out a solution on my own.
I have Paraview 5.3.0 and Light-Viz fresh from the repo.

thank you so much!
Rodrigo

**Comment by jourdain** [comment]
The Linux bundle of ParaView 5.3 is broken for ParaViewWeb usage. There is some missing dependency. ParaView 5.2 should be fine.

**Comment by rpelorosso** [comment]
Interesting, thank you! I'll try with 5.2
