### ISSUE TITLE
Setting up Data Directory in LightViz

### ISSUE THREAD

**Issue by Sagar-Shimpi** [Kitware/light-viz#71]
Hi,
I am very new to the ParaView, and struggling with importing data.
I am sorry if it's a very basic or stupid question.

I have installed LightViz on my linux virtual machine (I have already installed PV 5.5.2).
The problem is while generating data directory using command  "LightViz --data DATA_DIR --add-dataset path/to/dataset --description "Description of my data" its showing an error: 
ls: no such file or directory: /Applications
ls: no such file or directory: /usr/local/opt/

Please help me with this.
And also, may I know which path to put at "path/to/dataset".

Thank you in advance!

**Comment by jourdain** [comment]
You need to provide the path to ParaView using the `--paraview` argument.

Regarding the "path/to/dataset" should be based on what dataset you want to add into the database (DATA_DIR).

DATA_DIR is the directory where you want to gather all your datasets.

**Comment by Sagar-Shimpi** [comment]
Hi,
thanks for your reply.
I did as per your guidance.
I provided the path of ParaView using "LightViz --paraview /usr/bin/paraview".
I gave Data_Directory path using "LightViz --data /home/name/data_dir".
I tried adding datasets using "LightViz --add-dataset /home/name/datasets/surface.stl --description 'Description of dataset' ".

After executing all of this, what I am getting is this:

Usage: LightViz [options]


  Options:

    -V, --version                      output the version number
    -p, --port [8080]                  Start web server with given port (default: 8080)
    -d, --data [directory]             Data directory to serve
    -s, --server-only                  Do not open the web browser
    
    --paraview [path]                  Provide the ParaView root path to use
    --data-analysis                    Inspect data directory and compute metadata
    
    --config [path]                    Provide a Lightviz config file to use
    --profile [profile]                Specify which profile from the config file to use
    
    --add-dataset [path]               Specify a dataset to add to the given data directory.  Requires the description and data flags
    --description [description]        Specify the description for the dataset being added
    --autoApply                        Optional for use with --add-dataset.  Specifies that apply/reset buttons are not needed with the dataset
    --virtual-env [path]               Path to virtual environment to use
    --settings-lod-threshold [102400]  LOD Threshold in Megabytes

I am not getting whether the data directory is imported successfully or not.

I would be very grateful for your help.

**Comment by Sagar-Shimpi** [comment]
Thank you :).
The issue is solved.
