### ISSUE TITLE
problem on multiple user and multiple models

### ISSUE THREAD

**Issue by wangmeng1991** [Kitware/light-viz#74]
multiple models problem description:
when open two models (name Model A and Model B) at the same time, the first opened model (Model A) cannot be dragged any more. After refresh page of Model A, A can work but now Model B cannot be dragged.

multiple user problem description:
when two clients (C1 and C2) view the same page, C1 open first and then C2 open, problem is almost the same as above. When C2 drag, C1 can see the same move.

How to avoid this problem? Thanks

**Comment by wangmeng1991** [comment]
we are trying following this guide to solve multiple user problem but no result yet. But the multiple model problem seems no answer.
 https://kitware.github.io/paraviewweb/docs/multi_user_setup.html

**Comment by jourdain** [comment]
I am not sure to capture all the issues here, but it is true that if you have only one ParaView process serving all the clients, then it make sense that each client will edit the same session at the same time.

For the multi-model, I don't understand what you mean. Did you try ParaView-Visualizer? 

The docker images used in that [guide](https://kitware.github.io/paraviewweb/docs/ec2.html) already have the setup of the launcher and so on. Maybe looking at those docker images or even using them directly could help?
