### ISSUE TITLE
Light viz on windows 

### ISSUE THREAD

**Issue by Timanu05** [Kitware/light-viz#77]
Is it possible to run light viz on windows ? I've got this error when I use light viz command line:

![Capture](https://user-images.githubusercontent.com/44799668/84880537-ec9f6300-b08c-11ea-9ac9-c119d8fa82a7.PNG)

**Comment by jourdain** [comment]
I think the issue is that you need to provide the path to the ParaView to use `--paraview "C:\...\paraview\"`.

But in general LightViz was meant to show that custom web application could be made on top of ParaView. It is not supported anymore.

**Comment by Timanu05** [comment]
Thanks for your answer. I came back on paraview 5.2 to minimize errors due to new paraview versions but now I've got this: 

![Capture](https://user-images.githubusercontent.com/44799668/85298272-2e247980-b4a4-11ea-8977-3409c232e2a8.PNG)

It pops up a window and close it immediately without doing anything else.

**Comment by jourdain** [comment]
Can you rerun the same command line provided without the `--force-offscreen-rendering` argument?

**Comment by Timanu05** [comment]
I've got this:

![Capture](https://user-images.githubusercontent.com/44799668/85369342-3d9bd500-b52d-11ea-9c36-bc3931446d36.PNG)

**Comment by jourdain** [comment]
ParaView 5.2 is really old and might be too old for the version of LightViz.
When looking at the [compatibility](https://kitware.github.io/light-viz/docs/compatibility.html) you can see that 5.5 is the minimum requirement. Ideally I would even go with 5.6.

**Comment by Timanu05** [comment]
Oh right I didn't look that page. I manage to make it launch but my dataset doesn't appear on the browser screen. 
I have already set up my dataset as the [importing data section](https://kitware.github.io/light-viz/docs/setup.html) and I provide my data directory with the --data option:

![Capture](https://user-images.githubusercontent.com/44799668/85520177-d9e3db80-b602-11ea-8e32-bbe53090d004.PNG)

![Capture](https://user-images.githubusercontent.com/44799668/85519880-7659ae00-b602-11ea-9808-eb661277c2c3.PNG)

On screenshots you can see that I'm using 5.5 but I did try with 5.6 and I get the same result.

**Comment by jourdain** [comment]
Did you try to provide the data directory up to `\...\datadir\` without the `geometry` part?

**Comment by Timanu05** [comment]
I can select my dataset and indeed it gives me a view of my vtu with some modules on the left. But when I try basic camera interaction like hold left click to turn my geometry, it shut down the server and return this to the browser:

![Capture](https://user-images.githubusercontent.com/44799668/86239444-9f98b200-bb9f-11ea-8dbe-8137db18a162.PNG)

**Comment by jourdain** [comment]
What is the server log/output? Did you remove `--force-offscreen-rendering` like I asked you to?

**Comment by Timanu05** [comment]
Sorry I thought that now I could run the lightviz command line. It works now thanks you !
