### ISSUE TITLE
Paraviewweb: Does LightViz can load .pvsm file?

### ISSUE THREAD

**Issue by AaronFish007** [Kitware/light-viz#78]
Hi! I am new here and use paraviewweb lately to display OpenFOAM data. I found that I can successfully load .pvsm file in Visualizer, but the file cannot be loaded in Light-Viz. 

Does LightViz can load .pvsm file? And if not, is there another way to display OpenFOAM data in LightViz?

Thanks!

**Comment by yuanlin-yu** [comment]
Thanks for reply. If that's the case, it's there another way to display OpenFOAM results in LightViz? like transfer the data to .ex2 file or other way? Is there a good way? do you have good recommendation?

**Comment by jourdain** [comment]
You should be able to point to the OpenFOAM dataset directly. The format of the data should not matter as we use the readers available in ParaView. The file extension will be use to figure out which reader should be used. You just need to create the json descriptor either manually or with some kind of script.

**Comment by yuanlin-yu** [comment]
Thanks Jourdain. I can generate .foam dataset file now, but new problem coming out: the Light-Viz is staying at the “Loading Data” page. Is the file too large for the Light-Viz? Does the Light-Viz have limit of the size for data loading?

**Comment by yuanlin-yu** [comment]
Problem solve now! And find that the Light-Viz seems do not have legend for the color code?

**Comment by yuanlin-yu** [comment]
Light-Viz seems not have much as Visualizer, including can display different part of the geom, legend...

**Comment by jourdain** [comment]
LightViz is really a demo app meant to provide ideas. It is not really meant to be used in production.

**Comment by yuanlin-yu** [comment]
what a pity! the user interface of LightViz is very good. Anyway, thanks.
